version: '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    goadmin1: # For load balancer
        image: goapp
        environment: 
            - PORT=1111
    goadmin2:
        image: goapp
        environment: 
            - PORT=2222
    goadmin3:
        image: goapp
        environment: 
            - PORT=3333
    goadmin4:
        image: goapp
        environment: 
            - PORT=4444